### ISSUE TITLE
panics if new consumers are created in go routines and close is called

### ISSUE THREAD

**Issue by chandradeepak** [bsm/sarama-cluster#69]
If we create a 2 consumers in 2 go routines and both are using same GroupID and we call close for both them aysnc it triggers a panic in  sarama-cluster.

this is what i analyzed so far. 

In paritions.go in the function 
`func (c *partitionConsumer) Loop(messages chan<- *sarama.ConsumerMessage, errors chan<- error) {`

we are passing the channels messages and errors which are of the base consumer to partition consumer. And as soon as we get messages from partitions we are adding them to channel of   base consumer. But for some reason if the consumer is closed those channels are no longer valid and the partition consumer still gets any error or message it is going to add to a closed channel which panics.

How i got rid of it is by sending the dying channel as below to loop and select on a closed channel. that way i am not processing messages or errors if the main consumer died. This solved the panic . let me know what do you think of this.
`
func (c *partitionConsumer) Loop(messages chan<- *sarama.ConsumerMessage, errors chan<- error, dying <-chan none) {

	op := make(chan none)
	close(op)

	for {

		select {
		case _, ok := <-dying:
			if !ok {				
				return
			}
		case <-op:
			select {
			case msg := <-c.pcm.Messages():
				if msg != nil {
					select {
					case messages <- msg:
					case <-c.dying:
						close(c.dead)
						return
					}
				}
			case err := <-c.pcm.Errors():
				if err != nil {

					select {
					case <-c.dying:
						close(c.dead)
						return
					case errors <- err:

					}
				}
			case <-c.dying:
				close(c.dead)
				return
			}

		}

	}
}
`

`panic(0x4ed3a0, 0xc8204c7ab0)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
github.com/bsm/sarama-cluster.(*partitionConsumer).Loop(0xc820376410, 0xc820017380, 0xc820017320, 0xc820016e40)
github.com/bsm/sarama-cluster/partitions.go:59 +0x419
github.com/bsm/sarama-cluster.(*Consumer).createConsumer
github.com/bsm/sarama-cluster/consumer.go:634 +0x41c`

**Comment by dim** [comment]
Did you try the latest master or v2.1.0? It should be fixed there

**Comment by chandradeepak** [comment]
I tried latest version. It has fixes there. But still it doesn't fix the panic. That is because i am triggering a condition where the base  messages chan is closed before `c.pcm.Messages()` is closed.
`func (c *partitionConsumer) Loop(messages chan<- *sarama.ConsumerMessage, errors chan<- error) {`

I understand we are check `c.pcm.Messages()` channel close but we are not checking the base consumer channel close. So send on a closed channel panics. 

So i guess we need to check whether consumer is closed before pushing messages to its messages channel.

**Comment by dim** [comment]
So I understand the problem, but I cannot see any mistake in `Loop()`. We
definitely wait for the loop to return before closing the messages channel.
I don't see how we could be possibly stuck there. Can you see anything?

**Comment by chandradeepak** [comment]
i looked at code again. I understand that what are you doing is correct. But this is what i think is happening to cause the panic. 

In the sarama-cluster.Close we call sarama-cluster.release() which is supposed to stop all partition cosumers. only after that we call Close of the message channel. So theoretically this should not happen. Because in Loop you are checking only if the message channel is closed like this

`case msg, ok := <-c.pcm.Messages():
			if !ok {
				return
			}`

But if you look at sarama code they are no where calling sarama.partitionConsumer.messages Close. The close gets called only in the end of responseFeeder 
`close(child.messages)
close(child.errors)`

`func (child *partitionConsumer) Close() error {
	child.AsyncClose()

	go withRecover(func() {
		for _ = range child.messages {
			// drain
		}
	})

	var errors ConsumerErrors
	for err := range child.errors {
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return errors
	}
	return nil
}`

so until unless messages channel is close for sarama.ParitionConsumer the Loop code wont behave correctly.  That is why the panic happens.

**Comment by dim** [comment]
So even if sarama doesn't close its messages channel properly, that's still shouldn't be causing the issue. Let's do a quick review:

1. On `Close()` we first [release the subscriptions](https://github.com/bsm/sarama-cluster/blob/119e4039f85b356679309e735186b2fe9dcce177/consumer.go#L180), before we close the `messages` channel. 
2. In `release()` we `Stop()` all [consumers](https://github.com/bsm/sarama-cluster/blob/119e4039f85b356679309e735186b2fe9dcce177/consumer.go#L347).
3. `Stop()` then [closes all the partition consumers in parallel](https://github.com/bsm/sarama-cluster/blob/119e4039f85b356679309e735186b2fe9dcce177/partitions.go#L189), waiting for all to complete.
4. The `Close()` [method of a partition consumer](https://github.com/bsm/sarama-cluster/blob/119e4039f85b356679309e735186b2fe9dcce177/partitions.go#L70) does a few things. It stops the `sarama.PartitionConsumer` which may or may not exit the `Loop()` (as you have correctly identified). Additionally, it also closes the `dying` channel and *blocks until* for the `dead` channel is triggered.
5. The `dead` channel is only ever closed when the `Loop()` [exits](https://github.com/bsm/sarama-cluster/blob/119e4039f85b356679309e735186b2fe9dcce177/partitions.go#L42)

I really can't find a fault with this, but I have seen rare panics myself, that have then disappeared with my recent changes. Any more hints or advice would be more than welcome.

**Comment by dim** [comment]
I assume this is e.g. related: https://travis-ci.org/bsm/sarama-cluster/jobs/152894041. No `Loop()` should be running by the time `c.messages` is closed but apparently, there is. I cannot recreate the problem locally though.

**Comment by chandradeepak** [comment]
i will investigate more and find the path when it happens. Definitely some race condition . But thanks for your help so far.

**Comment by dim** [comment]
OK, I've got it, and it's not trivial :) Will update later today, thanks for the report.

**Comment by dim** [comment]
Fixed in https://github.com/bsm/sarama-cluster/commit/6d37f561b2a131e011c0cecf8a4d3c96b1e0a940

**Comment by chandradeepak** [comment]
this issue is fixed now i dont see the panics but i see clients are hanging. they are not getting data. Do you think because of this fix could there be a dead lock ?

Thanks for fixing it.

**Comment by dim** [comment]
Are you on the latest sarama version? Did you enable `sarama.Logger`? Any messages there?

**Comment by chandradeepak** [comment]
yes . i hav sarama Logger enabled

**Comment by dim** [comment]
no, what I meant is, are there any messages/logs that suggest a problem?

**Comment by chandradeepak** [comment]
no . i dont see any . let me dig more in to it. and i will update you.

**Comment by chandradeepak** [comment]
I couldn't reproduce it any further . it is good now. 
Thanks for the quick fix though.
