### ISSUE TITLE
Close() doesn't seem to be thread safe / idempotent

### ISSUE THREAD

**Issue by pneisen** [bsm/sarama-cluster#72]
I have multiple goroutines reading from a sarama-cluster.Consumer. On fatal errors during processing, I have the goroutines clean up. Part of this clean up is calling Close() on the Consumer from the goroutines. During a recent test, the calling of Close() by multiple goroutines in quick succession caused this panic:

```
panic: close of closed channel
goroutine 995 [running]:
panic(0x7a3d80, 0xc420840cf0)
    /usr/local/go/src/runtime/panic.go:500 +0x1a1
stash.keynetics.com/reap/collector.git/vendor/github.com/bsm/sarama-cluster.(*Consumer).Close(0xc42009a370, 0x0, 0x0)
    /home/gsp/projects/golang/src/stash.keynetics.com/reap/collector.git/vendor/github.com/bsm/sarama-cluster/consumer.go:177 +0x33
...
```

I think Close() should support being called multiple times without a panic. Does this seem reasonable? Or should I be making sure it only gets called once on my side and not by multiple goroutines at once?

**Comment by sudersen** [comment]
+1

Facing the same issues. Getting the below even for first **Close** call
`panic: close of closed channel`

**Comment by dim** [comment]
Fixed in https://github.com/bsm/sarama-cluster/commit/8c8649d2385454bdeb455c6a0765ff3ab2e2ea13, released as v2.1.3

**Comment by sudersen** [comment]
I'm sorry, still no luck. Getting the same error for **Close()** even after updating to v2.1.3
`"close of closed channel"`

Am I missing anything? On **SIGINT** or **SIGTERM** I simply call consumer.Close() which causes the aforementioned panic.

**Comment by dim** [comment]
Could you somehow try to break that test: https://github.com/bsm/sarama-cluster/blob/master/consumer_test.go#L193. I tried and it works for me

**Comment by sudersen** [comment]
@dim It works sleek! 
My bad. Had a wrong local patch. Sorry for the trouble.
